# Generated by Django 5.0.14 on 2026-04-16 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('order_number', models.CharField(help_text='Internt ordrenummer', max_length=100, unique=True, verbose_name='Ordrenummer')),
                ('supplier_reference', models.CharField(blank=True, help_text='Ordrenummer fra leverandør', max_length=100, verbose_name='Leverandørreferanse')),
                ('status', models.CharField(choices=[('DRAFT', 'Utkast'), ('ORDERED', 'Bestilt'), ('PARTIAL', 'Delvis mottatt'), ('RECEIVED', 'Fullstendig mottatt'), ('CANCELLED', 'Kansellert')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Bestillingsdato')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Forventet levering')),
                ('notes', models.TextField(blank=True, verbose_name='Notater')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.event', verbose_name='Event')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier', verbose_name='Leverandør')),
            ],
            options={
                'verbose_name': 'Innkjøpsordre',
                'verbose_name_plural': 'Innkjøpsordrer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='receivingorder',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Koble til eksisterende innkjøpsordre for delmottak', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_orders', to='inventory.purchaseorder', verbose_name='Innkjøpsordre'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('quantity_ordered', models.PositiveIntegerField(verbose_name='Bestilt antall')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Mottatt antall')),
                ('unit_cost_ore', models.IntegerField(help_text='Pris per enhet eks. mva i øre', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Enhetskost (øre)')),
                ('notes', models.TextField(blank=True, verbose_name='Notater')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Produkt')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder', verbose_name='Innkjøpsordre')),
            ],
            options={
                'verbose_name': 'Innkjøpsordrelinje',
                'verbose_name_plural': 'Innkjøpsordrelinjer',
            },
        ),
        migrations.AddField(
            model_name='receivingorderline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_lines', to='inventory.purchaseorderline', verbose_name='Fra innkjøpsordrelinje'),
        ),
    ]
