# Generated by Django 5.0.14 on 2026-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseorder_receivingorder_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='betala_general_ledger_account',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hovedbokskonto'),
        ),
        migrations.AddField(
            model_name='product',
            name='betala_is_bar_printing',
            field=models.BooleanField(default=False, verbose_name='Bar-utskrift'),
        ),
        migrations.AddField(
            model_name='product',
            name='betala_is_bundles',
            field=models.BooleanField(default=False, verbose_name='Er pakke'),
        ),
        migrations.AddField(
            model_name='product',
            name='betala_is_kitchen_printing',
            field=models.BooleanField(default=False, verbose_name='Kjøkken-utskrift'),
        ),
        migrations.AddField(
            model_name='product',
            name='betala_open_price',
            field=models.BooleanField(default=False, verbose_name='Åpen pris'),
        ),
        migrations.AddField(
            model_name='product',
            name='betala_organization_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Betala Org ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='betala_tag',
            field=models.IntegerField(default=1, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, help_text='Kategorinavn fra Betala', max_length=100, verbose_name='Kategori (tekst)'),
        ),
    ]
