# Generated by Django 5.0.14 on 2026-04-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_betala_general_ledger_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='betala_organization_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Betala Org ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='betala_product_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Betala Produkt ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='betala_tag',
            field=models.IntegerField(default=0, verbose_name='Tag (farge)'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('betala_product_id__isnull', False)), fields=('betala_organization_id', 'betala_product_id'), name='unique_product_per_org'),
        ),
    ]
