# Generated by Django 5.0.14 on 2026-04-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_betala_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='betala_previous_ids',
            field=models.JSONField(blank=True, default=list, help_text='Liste over tidligere Betala produkt-IDer (for sporing ved ID-endringer)', verbose_name='Tidligere Betala IDer'),
        ),
    ]
