# Generated by Django 5.0.14 on 2026-04-17 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_betala_previous_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_sales_sync',
            field=models.DateTimeField(blank=True, help_text='Når siste salgssync ble kjørt', null=True, verbose_name='Siste salgssynkronisering'),
        ),
        migrations.CreateModel(
            name='BetalaTransactionSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('sequence_number', models.IntegerField(db_index=True, help_text='Betala transaksjon sekvensnummer (unik per sales_point_group)', verbose_name='Sekvensnummer')),
                ('finalized_at', models.DateTimeField(help_text='Når transaksjonen ble avsluttet i Betala', verbose_name='Avsluttet')),
                ('is_void', models.BooleanField(default=False, help_text='Om transaksjonen er annullert/refundert', verbose_name='Annullert')),
                ('total_items', models.IntegerField(default=0, help_text='Totalt antall produkter solgt i denne transaksjonen', verbose_name='Antall varer')),
                ('total_amount_ore', models.IntegerField(default=0, verbose_name='Totalbeløp (øre)')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Synkronisert')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_transactions', to='inventory.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Betala transaksjon',
                'verbose_name_plural': 'Betala transaksjoner',
                'ordering': ['-finalized_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='betalatransactionsync',
            constraint=models.UniqueConstraint(fields=('event', 'sequence_number'), name='unique_transaction_per_event'),
        ),
    ]
