# Generated by Django 5.0.14 on 2026-04-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_sales_sync_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='betala_api_key',
            field=models.CharField(blank=True, help_text='API-nøkkel for automatisk synkronisering (valgfritt)', max_length=500, verbose_name='Betala API-nøkkel'),
        ),
    ]
