# Generated by Django 5.0.14 on 2026-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_betala_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False, help_text='Aktiver for å synkronisere salg automatisk hvert 15. min', verbose_name='Automatisk synkronisering'),
        ),
    ]
