# Generated by Django 5.0.14 on 2026-04-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_auto_sync_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='betala_sequence_number',
            field=models.IntegerField(blank=True, db_index=True, help_text='Transaksjonsnummer fra Betala for gruppering av salg', null=True, verbose_name='Betala trans.nr'),
        ),
    ]
