# Generated by Django 5.0.14 on 2026-04-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_betala_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='betala_bundle_product_ids',
            field=models.JSONField(blank=True, default=list, help_text='Liste over Betala produkt-IDer som inngår i pakken', verbose_name='Pakke-produkt IDer'),
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_products',
            field=models.ManyToManyField(blank=True, help_text='Produkter som inngår i denne pakken', related_name='part_of_bundles', to='inventory.product', verbose_name='Produkter i pakken'),
        ),
    ]
