# Generated by Django 5.0.14 on 2026-04-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_betala_bundle_product_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrinkageentry',
            name='recorded_loss_ore',
            field=models.IntegerField(blank=True, help_text='Estimert tap ved registreringstidspunkt', null=True, verbose_name='Registrert tap (øre)'),
        ),
    ]
