# Generated by Django 5.0.14 on 2026-04-17 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_recorded_loss_to_shrinkage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('quantity', models.IntegerField(verbose_name='Antall talt')),
                ('location', models.CharField(help_text='F.eks. "Bar 1", "Lager bak scene", "Kjølerom"', max_length=200, verbose_name='Posisjon/sted')),
                ('notes', models.TextField(blank=True, verbose_name='Notater')),
                ('counted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tidspunkt')),
                ('count_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_counts', to='inventory.stockcountline', verbose_name='Tellelinje')),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Talt av')),
            ],
            options={
                'verbose_name': 'Deltelling',
                'verbose_name_plural': 'Deltellinger',
                'ordering': ['counted_at'],
            },
        ),
    ]
