# Generated by Django 5.0.14 on 2026-04-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_partial_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcount',
            name='parent_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partial_counts', to='inventory.stockcount', verbose_name='Hovedtelling'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Pågår'), ('COMPLETED', 'Fullført'), ('CANCELLED', 'Avbrutt'), ('IMPORTED', 'Importert')], default='IN_PROGRESS', max_length=20, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='PartialCount',
        ),
    ]
