# Generated by Django 5.0.14 on 2026-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_update_stock_count_partials'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('betala_org_id', models.CharField(help_text='Organisasjonens ID i Betala (f.eks. 12345)', max_length=100, unique=True, verbose_name='Betala Org ID')),
                ('name', models.CharField(help_text='Navn på organisasjonen (for referanse)', max_length=200, verbose_name='Organisasjonsnavn')),
                ('identifier', models.CharField(blank=True, help_text='Organisasjonens identifier i Betala (valgfritt)', max_length=100, verbose_name='Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Deaktiver for å fjerne tilgang midlertidig', verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, help_text='Interne notater om organisasjonen', verbose_name='Notater')),
            ],
            options={
                'verbose_name': 'Godkjent organisasjon',
                'verbose_name_plural': 'Godkjente organisasjoner',
                'ordering': ['name'],
            },
        ),
    ]
