# Generated by Django 5.0.14 on 2026-04-20 11:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_allowed_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_unit_type',
            field=models.CharField(choices=[('ml', 'Milliliter'), ('cl', 'Centiliter'), ('stk', 'Stykk')], default='stk', help_text='Den minste enheten produktet lagres i (unngår avrundingsfeil)', max_length=10, verbose_name='Base-enhet'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_unit_conversion',
            field=models.BooleanField(default=False, help_text='Aktiver for produkter med flere enheter (f.eks. fatøl: Tank, Glass)', verbose_name='Bruk enhetskonvertering'),
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('name', models.CharField(help_text='F.eks. "Tank 30L", "Flaske 0.33L", "Glass 0.4L"', max_length=100, verbose_name='Enhetsnavn')),
                ('short_name', models.CharField(blank=True, help_text='F.eks. "Tank", "Fl", "Glass"', max_length=20, verbose_name='Kortform')),
                ('conversion_factor', models.PositiveIntegerField(help_text='Antall base-enheter (ml eller stk) denne enheten tilsvarer', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Konverteringsfaktor')),
                ('is_purchase_unit', models.BooleanField(default=False, help_text='Kan brukes ved innkjøp/varemottak', verbose_name='Innkjøpsenhet')),
                ('is_sale_unit', models.BooleanField(default=False, help_text='Brukes for salg fra Betala', verbose_name='Salgsenhet')),
                ('is_count_unit', models.BooleanField(default=True, help_text='Kan brukes ved varetelling', verbose_name='Telleenhet')),
                ('sort_order', models.IntegerField(default=0, help_text='Lavere tall = vises først (brukes for format_stock_display)', verbose_name='Sortering')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Enhet',
                'verbose_name_plural': 'Enheter',
                'ordering': ['product', 'sort_order', '-conversion_factor'],
            },
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_unit_name_per_product'),
        ),
    ]
