# Generated by Django 5.0.14 on 2026-04-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_unit_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingorderline',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Hvilken enhet ble brukt ved mottak (f.eks. Fat 300L)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_lines', to='inventory.unitofmeasure', verbose_name='Enhet'),
        ),
    ]
