# Generated by Django 5.0.14 on 2026-04-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_unit_to_receiving_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcountline',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Enheten som ble brukt ved telling', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasure', verbose_name='Enhet'),
        ),
    ]
