# Generated by Django 5.0.14

from django.db import migrations


def merge_stocklevel_locations(apps, schema_editor):
    """
    Slå sammen alle StockLevel med lokasjon til hovedraden (location='').
    Lokasjon skal bare brukes for organisering av tellinger, ikke for å splitte lager.
    """
    StockLevel = apps.get_model('inventory', 'StockLevel')
    
    # Finn alle StockLevel med lokasjon (ikke tom)
    location_levels = StockLevel.objects.exclude(location='')
    
    for level in location_levels:
        # Finn eller opprett hovedraden (utan lokasjon)
        main_level, created = StockLevel.objects.get_or_create(
            product=level.product,
            event=level.event,
            location='',
            defaults={'quantity': 0}
        )
        
        # Legg til beholdningen
        main_level.quantity += level.quantity
        main_level.save()
        
        # Slett den separate lokasjonsraden
        level.delete()


def reverse_merge(apps, schema_editor):
    # Kan ikke reverseres - manuell opprydding
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_add_unit_to_stock_count_line'),
    ]

    operations = [
        migrations.RunPython(merge_stocklevel_locations, reverse_merge),
    ]
